name 'themis-finals-service2-checker'
description 'Installs and configures Themis Finals service2 checker'
version '1.2.0'

recipe 'themis-finals-service2-checker', 'Installs and configures Themis Finals service2 checker'
depends 'latest-git', '~> 1.1.11'
depends 'git2', '~> 1.0.0'
depends 'supervisor', '~> 0.4.12'
depends 'modern_nginx', '~> 1.3.0'
depends 'ssh_known_hosts', '~> 2.0.0'
depends 'themis-finals-checker-app-py-lib', '~> 1.1.0'
depends 'themis-finals-checker-result-py-lib', '~> 1.1.0'
depends 'themis-finals-api-auth-py-lib', '~> 1.1.0'
depends 'ssh-private-keys', '~> 1.0.0'
