name 'themis-finals-sample-checker-py'
description 'Installs and configures Themis Finals sample Python checker'
version '1.1.9'

recipe 'themis-finals-sample-checker-py', 'Installs and configures Themis Finals sample Python checker'
depends 'latest-git', '~> 1.1.11'
depends 'git2', '~> 1.0.0'
depends 'supervisor', '~> 0.4.12'
depends 'modern_nginx', '~> 1.3.0'
depends 'ssh_known_hosts', '~> 2.0.0'
depends 'themis-finals', '~> 1.1.15'
